apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

        env:
        - name: POD_NAME
          valueFrom:
           fieldRef:
             fieldPath: metadata.name
   
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: APP_ENV

        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: USERNAME
        command: ["/bin/sh", "-c"]
        args:
          - echo "Hello from $POD_NAME" > /usr/share/nginx/html/index.html && nginx -g 'daemon off;';        
