apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1-deployment         # Deployment name
  labels:
    app: selecting-2-pod                  # Label for selecting pods
spec:
  replicas: 3                   # How many pods you want
  selector:
    matchLabels:
      app: mera-pod                # Which pods this deployment manages
  template:                         # Template to create pods
    metadata:
      labels:
        app: mera-pod             # Pod label (must match selector)
    spec:
      containers:
      - name: mahi-container   # Container name
        image: mq3274/mahi:latest  # Docker image
        ports:
        - containerPort: 3003     # Port exposed by the app
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password