apiVersion: v1
kind: Service
metadata:
  name: node-app-service            # Name of the service
spec:
  type: NodePort                    # Expose service on a port on each node
  selector:
    app: node-app                   # Must match the pod label
  ports:
    - protocol: TCP
      port: 3000                    # Port service exposes inside the cluster
      targetPort: 3000              # Port your app listens to inside the container
      nodePort: 32000               # Port exposed on your machine (between 30000-32767)
