apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep-node
  template:
    metadata:
      labels:
        app: dep-node
    spec:
      containers:
        - name: candy
          image: mq3274/candy-store2:v2
